### ISSUE TITLE
Commit 3ceb348a167b6c33f172a54098032c318af14509 introduced a regression

### ISSUE THREAD

**Issue by gevero** [bjornsturmberg/EMUstack#12]
Commit 3ceb348a167b6c33f172a54098032c318af14509 introduces a regression exactly [here](https://github.com/bjornsturmberg/EMUstack/blob/3ceb348a167b6c33f172a54098032c318af14509/backend/mode_calcs.py#L71), where after line 71 the return call has been deleted.

**Comment by bjornsturmberg** [comment]
Whoops!
Thanks for pointing that out! Corrected in 334d0aa
