### ISSUE TITLE
Cannot run tests

### ISSUE THREAD

**Issue by angel6700** [bjornsturmberg/EMUstack#19]
I'm tried to compile Suitesparse and all the required libraries, even gmsh.
Then, after making EMUstack.so, I went to the tests directory, and run nosetest:
This is the output:

```

./backend/materials.py:181: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  elif self.data_wls == 'Drude':
E

 ----------------------------------------------
 ----------------------------------------------
  Wavelength :   0.83333333333333337       (d)
  Wavelength :    1.6666666666666667       (d)
 ----------------------------------------------
 ----------------------------------------------


../backend/materials.py:181: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  elif self.data_wls == 'Drude':

 ----------------------------------------------
  Wavelength :   0.83333333333333337       (d)
 ----------------------------------------------

At line 132 of file conv_gmsh.f (unit = 24, file = '../backend/fortran/msh/500_0_500_0_120.msh')
Fortran runtime error: Bad integer for item 2 in list input

```

What could be causing this error?

Thank you in advance.

**Comment by bjornsturmberg** [comment]
Hi @angel6700  
I've tried to reproduce this error but the code is all working fine on my machine.
Can you please let me know what version of python, numpy, and gmsh you are using and whether you have been able to run other examples or your own simulations?
Thanks

**Comment by Simulator-CEM** [comment]
Briefly speaking, change the gmsh to v2.x, say gmsh-2.7.0-Linux64.

I believe it should be the version problem because I have also been face with this problem before. At first I use the Python2.7 and gmsh (v4.2), which are the default versions downloaded from the default ubantu library, the same error message appears, but if I turn to the mesh file named "***.mail", everything is fine, so I believe the problem should resulted from the gmsh. After roughly reading the source code of conv_gmsh.f, I manually download an older gmsh （gmsh-2.7.0-Linux64.zip) , and setup the EMUstack again, and this time it works!

**Comment by bjornsturmberg** [comment]
Thanks @Samson-Ming 
I have checked and my machine is running gmsh 3.0.6, which is consistent with your observation.
@angel6700 can you please try installing this version of gmsh and let us know if that solves the problem for you?

**Comment by bjornsturmberg** [comment]
Hi @Samson-Ming, 
How did you go with this? I made an update recently that should assist with mesh compatability with future versions of Gmsh, but updating to gmsh 3.0 is essential.

**Comment by Simulator-CEM** [comment]
> Hi @Samson-Ming,
> How did you go with this? I made an update recently that should assist with mesh compatability with future versions of Gmsh, but updating to gmsh 3.0 is essential.

Hi @bjornsturmberg 

Sure, I'll have try with the nuw version to see the mesh compatability, thanks😀!

Best regards

Xianshun
