### ISSUE TITLE
Error occurred in umf4zsym:   -8.0000000000000000

### ISSUE THREAD

**Issue by gevero** [bjornsturmberg/EMUstack#2]
### My system
- Scientific Linux 6 2.6.32-279.5.1.el6.x86_64
- gcc (GCC) 4.4.6 20110731 (Red Hat 4.4.6-3)
- SuitSparse 4.0.0
- metis 4.0
### compilation flags
- metis 4.0: -O3 -fPIC
- Suitsparse: -O3 -fexceptions -fPIC
- Lapack: -llapack
- Blas: -lblas -lgfortran

Everything compiles fine, the first test runs ok, and the second one exits with the message:
`Error occurred in umf4zsym:   -8.0000000000000000`
If I use the intel compiler, the test for the UMFPACK Demo segfaults, instead, if I change suitesparse to a more recent one, the second nosetest segfaults. Any ideas?

Best

Giovanni

**Comment by bjornsturmberg** [comment]
Hi Giovanni,

I am currently on holidays, I will look into this as soon as I return to
work on the 27th. From my phone my first comment would be to install an
older version of suitesparse.

Actually I just checked and the version of the documentation that github
links to is old. Here is a better version! This hopefully addresses both of
your emails.
http://emustack.readthedocs.org/en/v0.9.0/install.html

Apologies for these troubles, the linking to suitesparse is by far the most
annoying step!

**Comment by gevero** [comment]
Thank you so much for the prompt answer. I will try with an older suitesparse: I was just using 4.0 because it is first one with a `make install` target.  I will report back as soon as I have some news.

Best

Giovanni

**Comment by gevero** [comment]
As a followup I tried with SuiteSparse 3.7.1, without luck. The error seems to be the following:
UMFPACK ERROR invalid matrix(-8): The matrix is invalid. The full description of the error can be found [here](https://www.cise.ufl.edu/research/sparse/umfpack/UMFPACK/Doc/UserGuide.pdf) at page 24.

**Comment by gevero** [comment]
Just a brief followup: i get the same error on my 64 arch linux box. Therefore it must have something to do with the 64 bit nature of the machine.

**Comment by gevero** [comment]
Apparently I managed to make it work on my arch box with the suitesparse system library. Now I asked my sysadmin to install system suitesparse libraries on my servers. Let's see what happens.

**Comment by bjornsturmberg** [comment]
Thanks for the update. Fingers crossed!

**Comment by gevero** [comment]
I managed to solve the problem. Since I have no root privileges on my machines, I downloaded the needed rpm for for scientific linux 6.2 (atlas, atlas-dev, suitesparse, suitesparse-dev), and unpacked them in a local folder. After modifying LD_LIBRARIES_PATH, various Makefiles, etc... I finally have it working. I have a lot of questions for you...but they can wait.

Best

Giovanni

**Comment by bjornsturmberg** [comment]
Great news!

Please send your other questions to the Google group address and I will
answer them in just over a weeks time when I get home.
