### ISSUE TITLE
A proble about the period in EMUstack

### ISSUE THREAD

**Issue by Simulator-CEM** [bjornsturmberg/EMUstack#20]
Hi Professor Sturmberg,

I have a proble about the period in EMUstack when try to simulate some other structures by modifying the examples provided in the source code filefolder.

First I would like to modify the "simo_090-EOT.py" file to simulate a suspending subwavelength cross grating made of  an array of gold disks provided in "K. Edee et. al. JOSA A, 35(4):608-615,2018" with PMM (Polynomial modal motheod with matched coordiantes), and the modified file "simo_090-EOT-Edee.py" is also attached, and the structure parameters are listed below. 
————————————————————————————————————
Superstrate: 
                 Material: Air;  Thickness: semi_inf
Grating layer:
               Period: Square unit cell, Px=Py=700nm;
               Thickness: 50nm;
               Background: Air;  
               Inclusion: materials.Au_drude2 (insert "Au_drude2 = Material([1.37e16, 0.85e14,   
               3.7])" in "materials.py").
               Inclusion shape: circle;
               Diameter: 300nm;
Substrate: 
                 Material: Air;  Thickness: semi_inf

Incident light: 
             incident angle: normal incident, 0 [degree];
             azimuth angle: 0 [degree];
             polarzation: p (E field along x);
             frequency: f0=368 THz;
             wavelength: lam0=c/f0=1.163790597826087*700nm;

Reference refelction and transmission by PMM:
              R=0.900969507356113;
              T=0.002999846668958;
————————————————————————————————————
Thers is one thing quite weird, EMUstack functions well when I change the parmeters except when I change the period from the orignal 940nm in to 700nm in my structure (Note that I have commented the orignal mesh file "'4testing-940_266_sq.mail", and use "make_mesh_now = True" instead), a error message is give as "malloc(): invalid size (unsorted)". It seems that the simulation is case dependent related to the custom "#period must be consistent throughout simulation!!!" (?).

So at last I think of a very awkward way to warkaround this abstacle harnessing the metric invariance of Maxwell's equations, I multiple all the length related varibles by a factor of 940/700=1.342857142857143, thus the period is maintained to be 940nm. Meanwhile all the frequency related variables are multiplied by this factor, thus the permittivity of gold is set by materials.Au_drude3 (insert "Au_drude3 = Material([1.37e16/1.342857142857143, 0.85e14/1.342857142857143, 3.7]) " in "materials.py"), and f0=368/1.342857142857143 THz (lam0=1.163790597826087*940nm); This time it works, and by tunning "max_order_PWs " and "lc_bkg ", I increase the accuracy gradually at the price of longer simulation time. Finally with "max_order_PWs=10 " and "lc_bkg=0.12 ", I get a decent results below in about 50min with my laptop PC (Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz, 8GB RAM, Ubantu on Win10 x64)
————————————————————————————————————
Refelction and transmission by FEM modal method (EMUstack):
              R= 0.899659;
              T=0.004892;
Reference refelction and transmission by PMM:
              R=0.900969507356113;
              T=0.002999846668958;
————————————————————————————————————
I believe with finer mesh and larger truncted orders, the results can be better, but my computation source is inadequate. Neverthereness, it gives a relative good result with vivid physical meaning, the only point confusing me is the setting of periods.

[simo_090-EOT-Edee-2.zip](https://github.com/bjornsturmberg/EMUstack/files/5073246/simo_090-EOT-Edee-2.zip)

**Comment by gevero** [comment]
Could you try and use the jupyter notebook example, which already used gold nanodisks, to see what happens?

**Comment by Simulator-CEM** [comment]
Thank you, @gevero, but I didn't find the jupyter notebook example?

**Comment by gevero** [comment]
> Thank you, @gevero, but I didn't find the jupyter notebook example?

The example is in the examples folder and is called "nanodisk array with interpolators"

Best

Giovanni

**Comment by Simulator-CEM** [comment]
> > Thank you, @gevero, but I didn't find the jupyter notebook example?
> 
> The example is in the examples folder and is called "nanodisk array with interpolators"
> 
> Best
> 
> Giovanni

Sure，thanks， I'll have a try later.

**Comment by bjornsturmberg** [comment]
Hi Samson,
How did you go trying Giovanni's example (thanks for catching this Giovanni :)

**Comment by bjornsturmberg** [comment]
Hi @Samson-Ming,
How did you go trying Giovanni's example (thanks for catching this Giovanni :)

**Comment by Simulator-CEM** [comment]
> Hi @Samson-Ming,
> How did you go trying Giovanni's example (thanks for catching this Giovanni :)

Hi @bjornsturmberg , 
@gevero 
Yeah, I've tried Giovanni's example, but it seems still not working...

**Comment by gevero** [comment]
Hi @Samson-Ming 

It's not working, meaning that you get the same malloc result, or you get results that seem qualitatively off?

If you look at the spectrum calculated in the notebook example (Au disks, d=200mm, pitch=600nm, h=100nm) it looks remarkably similar to figure 2 of the cited paper (Au disks, d=300mm, pitch=700nm, h=500nm). Of course the reflectance peak is redshifted because you have thinner and wider disks. I will try to run the modified example myself.

Best

Giovanni

**Comment by Simulator-CEM** [comment]
Hi @gevero ,

It reports "malloc(): invalid size (unsorted)", I'm not sure about the mechanism, so it would be quite kind if you could try the modified example directly. Thank you so much!

Best regards

Samson

**Comment by gevero** [comment]
Hi @Samson-Ming 

I am working on it right now. It has been a long time since I have used EMUstack, so you'll have to be patient. EMUstack has amazing capabilities, but the compilation of the code is a bit finicky. I will be back to you as soon as I have a working setup and some new info.

Best

Giovanni

**Comment by iongbl** [comment]
Hi @Samson-Ming ,
I ran your example with power order=4 and period=700 and seems ok to me!
In the file Trans_EOT_h0.txt I find these values
  0.850000   0.578645
  1.163791   0.004892

Best regards
Ionut

**Comment by gevero** [comment]
Hi Ionut

How are things in Padova? I think that @Samson-Ming problem stems from some kind of compilation or library linking issue. I have to reinstall EMustack on my workstation and I will see if I match your results.

Best

Giovanni

**Comment by gevero** [comment]
Hi @Samson-Ming 

I run the calculation with the parameters used by Ionut, and the result looks pretty legit to me. The resonance position is slightly off, but we might need more plane wave expansions, a different mesh, or a different optical constant.
So maybe the error is due to your setup. Could you post:

- Your python distribution
- your blas and lapack kind and version
- your makefile
- your linux distro

So we can understand what is going wrong.

Best 

Giovanni

![image](https://user-images.githubusercontent.com/7213490/104199412-b27e2000-5427-11eb-9168-80b0ed392795.png)

**Comment by gevero** [comment]
@Samson-Ming 

One more thing, you could try the calculation with force_mesh=True

**Comment by Simulator-CEM** [comment]
> Hi @Samson-Ming
> 
> I run the calculation with the parameters used by Ionut, and the result looks pretty legit to me. The resonance position is slightly off, but we might need more plane wave expansions, a different mesh, or a different optical constant.
> So maybe the error is due to your setup. Could you post:
> 
> * Your python distribution
> * your blas and lapack kind and version
> * your makefile
> * your linux distro
> 
> So we can understand what is going wrong.
> 
> Best
> 
> Giovanni
> 
> ![image](https://user-images.githubusercontent.com/7213490/104199412-b27e2000-5427-11eb-9168-80b0ed392795.png)
Hi @gevero ,

I check the results, and it seems quite close to the referene by the PMM. So I think you are right, the problem should result from my settings of the EMustack itself (maybe because I'm not quite familiar with Linux). Unfortunatelely, I reinstall my system due to a collapse, and I hadn't restore the EMustack yet, so I need to reinstall and try it later.

Best regards

Samson

**Comment by iongbl** [comment]
Hi @Samson-Ming,
If you're a main windows user, you could also install EMUstack  inside the embedded Ubuntu kernel in Windows 10 and give it a try. 

Best regards,
Ionut

**Comment by gevero** [comment]
Hi @Samson-Ming 

If you have no more problems, I am going to close this issue.

Best

Giovanni
