### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [bjornsturmberg/EMUstack#23]
I suggest adding topics such as `physics`, `optics` in the About section at https://github.com/bjornsturmberg/EMUstack

**Comment by bjornsturmberg** [comment]
Thanks for the suggestion! I have added those topics now.



Kind Regards,

Bjorn Sturmberg
Senior Research Fellow, Battery Storage and Grid Integration Program

School of Engineering
College of Engineering, Computing and Cybernetics
Australian National University
Canberra, ACT 2601, Australia

+61 434 967 512
***@***.***
________________________________
From: Beliavsky ***@***.***>
Sent: Tuesday, 20 February 2024 9:02
To: bjornsturmberg/EMUstack ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [bjornsturmberg/EMUstack] add topics (Issue #23)


I suggest adding topics such as physics, optics in the About section at https://github.com/bjornsturmberg/EMUstack
