### ISSUE TITLE
Have trouble with running example files of EMUstack in docker container

### ISSUE THREAD

**Issue by Simulator-CEM** [bjornsturmberg/EMUstack#25]
Hi Professor Pellegrini and Professor Sturmberg,

I'm using a Win10 OS, and it seems that the docker container can be a more convenient method to run the EMUstack files. I have followed the instructions to install the docker step by step, and it seems that I have succeeded in constructing the framework. 

But unfortunately, I failed to run the test and example file with the container even with hard search on the internet due to poor knowledge on docker. So could you please show me a a demo program of how to command on the "Exec" window to run the python programs of gratings? Thank you so much.

Xianshun

PS: below is a snapshot of the docker container "Exec" window I got:

![1720790129263](https://github.com/user-attachments/assets/ae8e8f7c-9a0d-4242-8afc-7f534eb91e35)

**Comment by gevero** [comment]
You did everything correctly. Just `cd EMUstack/examples` and then `python whatever_example.py`

**Comment by Simulator-CEM** [comment]
Hi Prof Pellegrini,

There seems still some wrong with command "python" as below:

sh-5.2# bash
[root@9124113cc79f home]# cd /home/EMUstack/examples
[root@9124113cc79f examples]# python simo_010-single_interface.py
bash: python: command not found
[root@9124113cc79f examples]# ^C
[root@9124113cc79f examples]# python2 --version
bash: python2: command not found
[root@9124113cc79f examples]# python3 --version
Python 3.12.4
[root@9124113cc79f examples]# sudo apt install python3-pip
sudo: apt: command not found
[root@9124113cc79f examples]# pip3 --version
pip 23.2.1 from /usr/lib/python3.12/site-packages/pip (python 3.12)
[root@9124113cc79f examples]# python2 --version
bash: python2: command not found

![image](https://github.com/user-attachments/assets/32ad2ea7-aac0-4357-8d5b-26ab87184980)

**Comment by Simulator-CEM** [comment]
It seems work with “python3 simo_010-single_interface.py”

**Comment by Simulator-CEM** [comment]
Hi Professor Pellegrini and Professor Sturmberg,

It seems that I have acquired the correct results with EMUstack when compared with other methods like the RCWA. It is really wonderful to get the Bloch mode directly and solve the diffraction efficiencies directly with a method similar to the analytical modal method in 1D grating, thank you so much!

Still I have some thoughts on EMUstack for your judgment:

1. It seems that EMUstack currently doesn't consider the symmetry yet which could reduce the computation burden.

2. I am not quite sure the number of Bloch mode (both the waveguide mode in patterned layer and plane waves in the unpatterned layer) can vary in different layers. I remember that this number can be different in different layers in the 1D grating where only reserving several leading terms in the very deep and high contrast dielectric layer subwavelength grating is enough to obtain decent results, which results in the physically clear "Simplified modal method". I believe this issue should be meaningful because nowadays when people design their all-dielectric metasurface, their meta-atom usually belongs to this situation, and I believe the number should be large in the superstrate and substrate but small in the patterned grating layer, which may also accelerate the overlap integrating process and the whole algorithm.
