### ISSUE TITLE
heights_nm attribute in Stack objects

### ISSUE THREAD

**Issue by gevero** [bjornsturmberg/EMUstack#9]
EMUstack provides a facility to easily variate the thickness of a layer inside of a stack, as seen in the [docs](http://emustack.readthedocs.org/en/master/tutorial.html#varying-a-layer-of-a-stack), via the instruction:

``` python
stackSub = Stack((sim_sub, sim_NWs, sim_cover), heights_nm = ([h]))
```

Yet the layers of `stackSub`, i.e. the instance of the `Stack` objects, retain their original `height_nm`, as can be checked via `stackSub.layers[1].structure.height_nm`. This does not create major problems, with one notable exception: when trying to plot a vertical section of the local field, all the subroutine plots are bounded by the `layer.structure.height_nm` attribute, and not by the `stack.heights_nm` one. A possible fix is to update the layer heights via something like

``` python
for i_lay,lay in enumerate(self.layers[1:-1]]):
    lay.structure.height_nm = heights_nm[i_lay+1]
```

So that the returned instance stackSub has the correct heights for each layer.
Please let me know if for you it could work.

**Comment by bjornsturmberg** [comment]
Thanks for your suggestion.
I have made the following addition in stack.py in commit 429eecb

``` python
for i_lay, lay in enumerate(self.layers[1:-1]):
    lay.structure.height_nm = heights_nm[i_lay]
```

Note that there is only a single layer instance so consecutively created Stacks will override the layers height_nm.
